
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ATManager.Models
{

using System;
    using System.Collections.Generic;
    
public partial class AT_IndiciValutazione
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public AT_IndiciValutazione()
    {

        this.AT_SchedaTecnica = new HashSet<AT_SchedaTecnica>();

        this.AT_SchedaTecnica1 = new HashSet<AT_SchedaTecnica>();

        this.AT_SchedaTecnica2 = new HashSet<AT_SchedaTecnica>();

        this.AT_SchedaTecnica3 = new HashSet<AT_SchedaTecnica>();

        this.AT_SchedaTecnica4 = new HashSet<AT_SchedaTecnica>();

        this.AT_SchedaTecnica5 = new HashSet<AT_SchedaTecnica>();

        this.AT_SchedaTecnica6 = new HashSet<AT_SchedaTecnica>();

        this.AT_SchedaTecnica7 = new HashSet<AT_SchedaTecnica>();

        this.AT_SchedaTecnica8 = new HashSet<AT_SchedaTecnica>();

        this.AT_SchedaTecnica9 = new HashSet<AT_SchedaTecnica>();

        this.AT_SchedaTecnica10 = new HashSet<AT_SchedaTecnica>();

        this.AT_SchedaTecnica11 = new HashSet<AT_SchedaTecnica>();

        this.AT_SchedaTecnica12 = new HashSet<AT_SchedaTecnica>();

        this.AT_SchedaTecnica13 = new HashSet<AT_SchedaTecnica>();

        this.AT_SchedaTecnica14 = new HashSet<AT_SchedaTecnica>();

        this.AT_SchedaTecnica15 = new HashSet<AT_SchedaTecnica>();

        this.AT_SchedaTecnica16 = new HashSet<AT_SchedaTecnica>();

        this.AT_SchedaTecnica17 = new HashSet<AT_SchedaTecnica>();

        this.AT_SchedaTecnica19 = new HashSet<AT_SchedaTecnica>();

        this.AT_SchedaTecnica20 = new HashSet<AT_SchedaTecnica>();

        this.AT_SchedaTecnica21 = new HashSet<AT_SchedaTecnica>();

        this.AT_SchedaTecnica22 = new HashSet<AT_SchedaTecnica>();

        this.AT_SchedaTecnica23 = new HashSet<AT_SchedaTecnica>();

        this.AT_SchedaTecnica24 = new HashSet<AT_SchedaTecnica>();

        this.AT_SchedaTecnica25 = new HashSet<AT_SchedaTecnica>();

        this.AT_SchedaTecnica26 = new HashSet<AT_SchedaTecnica>();

        this.AT_SchedaTecnica27 = new HashSet<AT_SchedaTecnica>();

        this.AT_SchedaTecnica28 = new HashSet<AT_SchedaTecnica>();

        this.AT_SchedaTecnica29 = new HashSet<AT_SchedaTecnica>();

        this.AT_SchedaTecnica30 = new HashSet<AT_SchedaTecnica>();

        this.AT_SchedaTecnica31 = new HashSet<AT_SchedaTecnica>();

        this.AT_SchedaTecnica32 = new HashSet<AT_SchedaTecnica>();

        this.AT_SchedaTecnica33 = new HashSet<AT_SchedaTecnica>();

        this.AT_SchedaTecnica34 = new HashSet<AT_SchedaTecnica>();

        this.AT_SchedaTecnica35 = new HashSet<AT_SchedaTecnica>();

        this.AT_SchedaTecnica36 = new HashSet<AT_SchedaTecnica>();

        this.AT_SchedaTecnica37 = new HashSet<AT_SchedaTecnica>();

        this.AT_SchedaTecnica38 = new HashSet<AT_SchedaTecnica>();

        this.AT_SchedaTecnica39 = new HashSet<AT_SchedaTecnica>();

        this.AT_SchedaTecnica40 = new HashSet<AT_SchedaTecnica>();

        this.AT_SchedaTecnica111 = new HashSet<AT_SchedaTecnica>();

        this.AT_SchedaTecnica401 = new HashSet<AT_SchedaTecnica>();

        this.AT_SchedaTecnica181 = new HashSet<AT_SchedaTecnica>();

    }


    public int ID { get; set; }

    public string Descr { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AT_SchedaTecnica> AT_SchedaTecnica { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AT_SchedaTecnica> AT_SchedaTecnica1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AT_SchedaTecnica> AT_SchedaTecnica2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AT_SchedaTecnica> AT_SchedaTecnica3 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AT_SchedaTecnica> AT_SchedaTecnica4 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AT_SchedaTecnica> AT_SchedaTecnica5 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AT_SchedaTecnica> AT_SchedaTecnica6 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AT_SchedaTecnica> AT_SchedaTecnica7 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AT_SchedaTecnica> AT_SchedaTecnica8 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AT_SchedaTecnica> AT_SchedaTecnica9 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AT_SchedaTecnica> AT_SchedaTecnica10 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AT_SchedaTecnica> AT_SchedaTecnica11 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AT_SchedaTecnica> AT_SchedaTecnica12 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AT_SchedaTecnica> AT_SchedaTecnica13 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AT_SchedaTecnica> AT_SchedaTecnica14 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AT_SchedaTecnica> AT_SchedaTecnica15 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AT_SchedaTecnica> AT_SchedaTecnica16 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AT_SchedaTecnica> AT_SchedaTecnica17 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AT_SchedaTecnica> AT_SchedaTecnica19 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AT_SchedaTecnica> AT_SchedaTecnica20 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AT_SchedaTecnica> AT_SchedaTecnica21 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AT_SchedaTecnica> AT_SchedaTecnica22 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AT_SchedaTecnica> AT_SchedaTecnica23 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AT_SchedaTecnica> AT_SchedaTecnica24 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AT_SchedaTecnica> AT_SchedaTecnica25 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AT_SchedaTecnica> AT_SchedaTecnica26 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AT_SchedaTecnica> AT_SchedaTecnica27 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AT_SchedaTecnica> AT_SchedaTecnica28 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AT_SchedaTecnica> AT_SchedaTecnica29 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AT_SchedaTecnica> AT_SchedaTecnica30 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AT_SchedaTecnica> AT_SchedaTecnica31 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AT_SchedaTecnica> AT_SchedaTecnica32 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AT_SchedaTecnica> AT_SchedaTecnica33 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AT_SchedaTecnica> AT_SchedaTecnica34 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AT_SchedaTecnica> AT_SchedaTecnica35 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AT_SchedaTecnica> AT_SchedaTecnica36 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AT_SchedaTecnica> AT_SchedaTecnica37 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AT_SchedaTecnica> AT_SchedaTecnica38 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AT_SchedaTecnica> AT_SchedaTecnica39 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AT_SchedaTecnica> AT_SchedaTecnica40 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AT_SchedaTecnica> AT_SchedaTecnica111 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AT_SchedaTecnica> AT_SchedaTecnica401 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AT_SchedaTecnica> AT_SchedaTecnica181 { get; set; }

}

}
