
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ATManager.Models
{

using System;
    using System.Collections.Generic;
    
public partial class AT_ListaPraticheSenzaPerizia_vw
{

    public string Targa { get; set; }

    public string ID_Gestione { get; set; }

    public Nullable<int> ID { get; set; }

}

}
