
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ATManager.Models
{

using System;
    using System.Collections.Generic;
    
public partial class AT_ListaPratiche_vw
{

    public Nullable<int> TipoPerizia_ID { get; set; }

    public string TipoPerizia_Descr { get; set; }

    public int PRAT_ID { get; set; }

    public string Targa { get; set; }

    public string Chassis1 { get; set; }

    public string Chassis2 { get; set; }

    public string ID_Produttore { get; set; }

    public string ID_LuogoIntervento { get; set; }

    public string DescrITA { get; set; }

    public string dealerPiazzale_peritoNonTabellato { get; set; }

    public string indirizzo_peritoNonTabellato { get; set; }

    public string citta_peritoNonTabellato { get; set; }

    public string Perizie_Barcode { get; set; }

    public string Perizie_IDPerito { get; set; }

    public int Perizie_ID { get; set; }

    public Nullable<bool> Perizie_IsChiusa { get; set; }

    public Nullable<bool> Perizie_IsChecked { get; set; }

    public Nullable<System.DateTime> Perizie_DataIncarico { get; set; }

    public Nullable<System.DateTime> Perizie_DataPerizia { get; set; }

    public string Perizie_Note { get; set; }

    public Nullable<bool> IsPdf { get; set; }

    public Nullable<bool> IsFoto { get; set; }

    public string ID_UltimoStato { get; set; }

    public string UltimoStato { get; set; }

    public string DescStato { get; set; }

    public string AO_Cognome { get; set; }

    public string AO_Nome { get; set; }

    public string Mod_Descr { get; set; }

    public string Prod_ID { get; set; }

    public string Prod_Descr { get; set; }

    public Nullable<int> ID_SchedaTecnica { get; set; }

    public Nullable<System.DateTime> DataImmatricolazione { get; set; }

    public Nullable<int> Km { get; set; }

    public Nullable<bool> IsCompleted { get; set; }

    public string UltimoStatus { get; set; }

    public string CartaCircolazione { get; set; }

    public string Matricola { get; set; }

    public Nullable<System.DateTime> DataUltimaRevisione { get; set; }

    public string Trilettera { get; set; }

    public Nullable<int> ID_AziendaUtilizzatrice { get; set; }

    public string DescrizioneAzienda { get; set; }

}

}
