
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ATManager.Models
{

using System;
    using System.Collections.Generic;
    
public partial class AT_PreventiviDanno
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public AT_PreventiviDanno()
    {

        this.AT_SchedaTecnica = new HashSet<AT_SchedaTecnica>();

    }


    public int ID { get; set; }

    public string Descr { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AT_SchedaTecnica> AT_SchedaTecnica { get; set; }

}

}
