
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ATManager.Models
{

using System;
    using System.Collections.Generic;
    
public partial class AT_PeritiXZone
{

    public int ID { get; set; }

    public Nullable<int> ID_Perito { get; set; }

    public string ID_zona { get; set; }

    public string UserName { get; set; }

}

}
