
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ATManager.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SDU_Pratiche
{

    public int ID { get; set; }

    public string ID_Gestione { get; set; }

    public string Barcode { get; set; }

    public string PreventivoNum { get; set; }

    public Nullable<System.DateTime> DataApertura { get; set; }

    public Nullable<int> OraApertura { get; set; }

    public Nullable<int> MinApertura { get; set; }

    public Nullable<System.DateTime> DataPrimoAccesso { get; set; }

    public Nullable<System.DateTime> DataChiusura { get; set; }

    public string ID_ClienteDCliente { get; set; }

    public Nullable<int> ID_LuogoInt { get; set; }

    public string ID_Produttore { get; set; }

    public string ID_Modello { get; set; }

    public Nullable<int> ID_Versione { get; set; }

    public string Targa { get; set; }

    public string TargaCheck { get; set; }

    public Nullable<int> ID_TipoSinistro { get; set; }

    public Nullable<int> ID_Perito { get; set; }

    public Nullable<int> ID_AziendaUtilizzatrice { get; set; }

    public string Note { get; set; }

    public string Insert_Usr { get; set; }

    public Nullable<System.DateTime> Insert_Time { get; set; }

    public string Update_Usr { get; set; }

    public Nullable<System.DateTime> Update_Time { get; set; }

    public string ID_Societa { get; set; }

    public Nullable<int> CountGruppoPratiche { get; set; }

    public Nullable<int> Km { get; set; }

    public string Chassis1 { get; set; }

    public Nullable<int> ID_Colore { get; set; }

    public string Parcheggio { get; set; }

    public Nullable<bool> IsChiusa { get; set; }

    public string Rif_fattura { get; set; }

    public Nullable<bool> IsFatt_Att { get; set; }

    public Nullable<bool> IsFatt_Pass { get; set; }

    public Nullable<System.DateTime> DataFattAtt { get; set; }

    public Nullable<System.DateTime> DataFattPass { get; set; }

    public Nullable<double> ImportoFattAtt { get; set; }

    public Nullable<double> ImportoFattPass { get; set; }

    public string Chassis2 { get; set; }

    public string VersioneCliente { get; set; }

    public string ID_SocProp { get; set; }

    public string ID_TipoVeicolo { get; set; }

    public Nullable<int> ID_TipoAlimentazione { get; set; }

    public Nullable<System.DateTime> DataImmatricolazione { get; set; }

    public Nullable<int> ID_Posti { get; set; }

    public Nullable<int> ID_Porte { get; set; }

    public Nullable<int> ID_TipoCambio { get; set; }

    public Nullable<int> ID_NumeroMarce { get; set; }

    public string PotenzaMotoreCV { get; set; }

    public string PotenzaMotoreKW { get; set; }

    public string ColoreInterni { get; set; }

    public Nullable<int> ID_TipoInterni { get; set; }

    public Nullable<int> ID_TipoVernice { get; set; }

    public Nullable<bool> is23finenolo { get; set; }

    public Nullable<int> Cilindrata { get; set; }

    public Nullable<double> Lunghezza { get; set; }

    public string SiglaEuro { get; set; }



    public virtual SDU_Pratiche SDU_Pratiche1 { get; set; }

    public virtual SDU_Pratiche SDU_Pratiche2 { get; set; }

}

}
