
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ATManager.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SDU_StoricoStatusPerizia
{

    public int ID { get; set; }

    public int IDPerizia { get; set; }

    public string IDStato { get; set; }

    public Nullable<System.DateTime> Data { get; set; }

    public Nullable<int> Importo { get; set; }

    public string InsertUser { get; set; }

    public System.DateTime InsertTime { get; set; }

    public string Note { get; set; }

    public Nullable<int> Giorni { get; set; }

    public string MassimoID { get; set; }

    public long Ordine { get; set; }

}

}
