
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ATManager.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SDU_Perizie
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SDU_Perizie()
    {

        this.AT_SchedaTecnica = new HashSet<AT_SchedaTecnica>();

    }


    public int ID { get; set; }

    public string Barcode { get; set; }

    public int ID_Pratica { get; set; }

    public string ID_Perito { get; set; }

    public Nullable<int> ID_TipoPerizia { get; set; }

    public string ID_LuogoIntervento { get; set; }

    public Nullable<int> ID_Meteo { get; set; }

    public Nullable<System.DateTime> DataIncarico { get; set; }

    public Nullable<System.DateTime> DataPerizia { get; set; }

    public Nullable<double> Imp_IC { get; set; }

    public Nullable<double> Imp_Produttore { get; set; }

    public Nullable<double> Delta_IC_Prod { get; set; }

    public Nullable<double> ImportoA { get; set; }

    public Nullable<double> ImpTotStima { get; set; }

    public string Note { get; set; }

    public string Note2 { get; set; }

    public Nullable<bool> IsChiusa { get; set; }

    public string RifFatturaAtt { get; set; }

    public Nullable<bool> IsFatt_Att { get; set; }

    public Nullable<bool> IsFatt_Pass { get; set; }

    public Nullable<System.DateTime> DataFattAtt { get; set; }

    public Nullable<System.DateTime> DataFattPass { get; set; }

    public Nullable<double> ImportoFattAtt { get; set; }

    public Nullable<double> ImportoFattPass { get; set; }

    public string Insert_Usr { get; set; }

    public Nullable<System.DateTime> Insert_Time { get; set; }

    public string Update_Usr { get; set; }

    public Nullable<System.DateTime> Update_Time { get; set; }

    public string Update_Usr_Fiat { get; set; }

    public Nullable<System.DateTime> Update_Time_Fiat { get; set; }

    public Nullable<int> Km { get; set; }

    public Nullable<int> KM_Incarico { get; set; }

    public Nullable<bool> IsBatteriaScarica { get; set; }

    public string PosizionePiazzale { get; set; }

    public Nullable<int> ID_Visibilita { get; set; }

    public Nullable<bool> IsChecked { get; set; }

    public string RifFatturaPass { get; set; }

    public Nullable<System.DateTime> DataScadenza { get; set; }

    public string ID_Cedente { get; set; }

    public Nullable<bool> IsImpProd { get; set; }

    public Nullable<int> ID_FotoTarga { get; set; }

    public Nullable<int> ID_FotoVIN { get; set; }

    public Nullable<bool> IsInviate { get; set; }

    public Nullable<int> ID_FotoKm { get; set; }

    public Nullable<int> ID_FotoAngAntSX { get; set; }

    public Nullable<int> ID_FotoAngPostSX { get; set; }

    public Nullable<int> ID_FotoAngPostDX { get; set; }

    public Nullable<int> ID_FotoAngAntDX { get; set; }

    public Nullable<int> INI_NumeroPratiche_File { get; set; }

    public Nullable<System.DateTime> INI_DataGenerazione_File { get; set; }

    public string INI_TipologiaIncarico_File { get; set; }

    public Nullable<int> INI_Contratto_File { get; set; }

    public string INI_Dealer_File { get; set; }

    public string INI_RiferimentoDealer_File { get; set; }

    public string INI_Deposito_File { get; set; }

    public string INI_RiferimentoDeposito_File { get; set; }

    public string INI_Trasportatore_File { get; set; }

    public string INI_RiferimentoTrasportatore_File { get; set; }

    public string INI_Veicolo_File { get; set; }

    public string INI_Colore_File { get; set; }

    public Nullable<int> INI_Km_File { get; set; }

    public string INI_Targa_File { get; set; }

    public string INI_Telaio_File { get; set; }

    public Nullable<System.DateTime> INI_DataImmatricolazione_File { get; set; }

    public Nullable<System.DateTime> INI_DataRiconsegna_File { get; set; }

    public Nullable<System.DateTime> INI_DataStock_File { get; set; }

    public Nullable<System.DateTime> INI_DataIncarico_File { get; set; }

    public Nullable<System.DateTime> INI_InsTime_File { get; set; }

    public Nullable<System.DateTime> PrimaGenXSL { get; set; }

    public Nullable<System.DateTime> SPA_DataSpacc { get; set; }

    public Nullable<double> SPA_PeriziaCompleta { get; set; }

    public string SPA_Denunciato1 { get; set; }

    public string SPA_NumSinistro1 { get; set; }

    public Nullable<System.DateTime> SPA_DataSinistro1 { get; set; }

    public string SPA_Denunciato2 { get; set; }

    public string SPA_NumSinistro2 { get; set; }

    public Nullable<System.DateTime> SPA_DataSinistro2 { get; set; }

    public string SPA_Denunciato3 { get; set; }

    public string SPA_NumSinistro3 { get; set; }

    public Nullable<System.DateTime> SPA_DataSinistro3 { get; set; }

    public string SPA_Denunciato4 { get; set; }

    public string SPA_NumSinistro4 { get; set; }

    public Nullable<System.DateTime> SPA_DataSinistro4 { get; set; }

    public Nullable<double> SPA_TotDanDen { get; set; }

    public Nullable<double> SPA_AttrDealer { get; set; }

    public Nullable<double> SPA_AttrTrasp { get; set; }

    public Nullable<double> SPA_AttrPiazz { get; set; }

    public Nullable<double> SPA_DanLog { get; set; }

    public Nullable<double> SPA_DanGom50 { get; set; }

    public string SPA_NonDen { get; set; }

    public string SPA_DanMec { get; set; }

    public string SPA_DanInt { get; set; }

    public string SPA_Note { get; set; }

    public string SPA_Utente { get; set; }

    public string ImpRichiesto { get; set; }

    public string ImpConcordato { get; set; }

    public Nullable<double> ImpDanni { get; set; }

    public string PerizieEsterne { get; set; }

    public Nullable<bool> IsFoto { get; set; }

    public Nullable<bool> IsPdf { get; set; }

    public Nullable<bool> IsPdf_PerTot { get; set; }

    public Nullable<bool> IsIncaricoUff { get; set; }

    public Nullable<System.DateTime> DataFaseA { get; set; }

    public Nullable<System.DateTime> DataFaseB { get; set; }

    public Nullable<bool> IsStorico { get; set; }

    public Nullable<bool> IsAutorizzata { get; set; }

    public string NoteAutoriz { get; set; }

    public Nullable<bool> IsTxT { get; set; }

    public Nullable<System.DateTime> DataInvioAdzImplant { get; set; }

    public Nullable<double> QuotaOraria { get; set; }

    public Nullable<double> ValoreCommerciale { get; set; }

    public Nullable<double> ValoreRelitto { get; set; }

    public Nullable<bool> IsInProvincia { get; set; }

    public Nullable<bool> IsFlagFranchigia { get; set; }

    public string MailIncaricoR { get; set; }

    public Nullable<bool> IsInSpacc { get; set; }

    public Nullable<bool> IsRichIncUff { get; set; }

    public Nullable<System.DateTime> DataRicezionePerizia { get; set; }

    public Nullable<System.DateTime> DataInvioIncarico { get; set; }

    public string UserInvioIncarico { get; set; }

    public Nullable<double> BonusPass { get; set; }

    public Nullable<double> MalusPass { get; set; }

    public Nullable<int> DeltaPass { get; set; }

    public Nullable<bool> IsRispacchettata { get; set; }

    public Nullable<double> ImportoBasePass { get; set; }

    public Nullable<bool> IsFatt_AttSpacc { get; set; }

    public Nullable<bool> IsFatt_PassSpacc { get; set; }

    public Nullable<System.DateTime> DataFattAttSpacc { get; set; }

    public Nullable<System.DateTime> DataFattPassSpacc { get; set; }

    public string RifFatturaAttSpacc { get; set; }

    public string RifFatturaPassSpacc { get; set; }

    public Nullable<bool> IsFatt_AttRisp { get; set; }

    public Nullable<bool> IsFatt_PassRisp { get; set; }

    public Nullable<System.DateTime> DataFattAttRisp { get; set; }

    public Nullable<System.DateTime> DataFattPassRisp { get; set; }

    public string RifFatturaAttRisp { get; set; }

    public string RifFatturaPassRisp { get; set; }

    public Nullable<double> ImportoFattPassSpacc { get; set; }

    public Nullable<double> ImportoFattPassRisp { get; set; }

    public Nullable<double> ImportoFattAttSpacc { get; set; }

    public Nullable<bool> ControlloFunzionale_ok { get; set; }

    public Nullable<bool> ControlloFunzionale_anom { get; set; }

    public string ID_UltimoStato { get; set; }

    public Nullable<bool> SmartRepair { get; set; }

    public Nullable<double> ImportoRivalutazione { get; set; }

    public Nullable<bool> DisaccordoPeritoFlag { get; set; }

    public Nullable<int> KmMedio { get; set; }

    public Nullable<System.DateTime> DataPubblicazionePerizia { get; set; }

    public string FromIncaricoR { get; set; }

    public string ccIncaricoR { get; set; }

    public string OggIncaricoR { get; set; }

    public Nullable<bool> Is_NonFatturare { get; set; }

    public Nullable<System.DateTime> Is_InterventoMultiplo { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AT_SchedaTecnica> AT_SchedaTecnica { get; set; }

}

}
